Parameters:
  PublicSSGID:
    Type: String
    Description: "PublicSSGID from another stack securitygroup"
  publicSubnet1A:
    Type: String
    Description: "PublicSubnet1AID"
  PublicSubnet1B:
    Type: String
    Description: "PublicSubnet1BID"
  
  #TargetGroup:
    #Type: String
    #Description: "Targetgroupname"
  VPCID:
    Type: String
    Description: "VPCID for ALB"
    
  

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: MyALB
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref PublicSSGID
      Subnets: 
        - !Ref publicSubnet1A
        - !Ref PublicSubnet1B
      Type: application
  
  ALBListner:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
  
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      
      
      Name: TGCFNFORALB
      Port: 80
      Protocol: HTTP
      
      TargetGroupAttributes: 
        - Key: stickiness.enabled
          Value: true
        
      
      TargetType: instance
      VpcId: !Ref VPCID

Outputs:
     TGID:
      Description: "ARN of TargetGroup"
      Value: !Ref TargetGroup
      Export:
        Name: TGID

      


