Parameters:

  MyVPCCidrBlock:
    Type: String
    Description: "myVPC CIDR block"
    Default: 10.0.0.0/16

  PublicSubnetCidrBlock:
    Type: String
    Description: "myVPC CIDR block"
    Default: 10.0.1.0/24
  
  PrivateSubnetCidrBlock:
    Type: String
    Description: "myVPC CIDR block"
    Default: 10.0.3.0/24
  
  AZ:
    Description: "ParameterForAZ"
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a

Resources:



  myVPCCFN:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: myVPCCFN
  PrivateSubnetCFN:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      VpcId: !Ref myVPCCFN 
      CidrBlock: !Ref PrivateSubnetCidrBlock
      Tags:
        - Key: Name
          Value: PrivateSubnetCFN
  PublicSubnetCFN:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      VpcId: !Ref myVPCCFN
      CidrBlock: !Ref PublicSubnetCidrBlock
      Tags:
        - Key: Name
          Value: PublicSubnetCFN
  PublicNacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
        VpcId: !Ref myVPCCFN
        Tags:
        - Key: Name
          Value: PublicNacl
  
  InboundRuleForPublicNacl:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId: !Ref PublicNacl
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
       PortRange:
         From: 3389
         To: 3389
  OutboundRuleForPublicNacl:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
         NetworkAclId: !Ref PublicNacl
         RuleAction: allow
         RuleNumber: 100
         Protocol: 6
         Egress: true
         CidrBlock: 0.0.0.0/0
         PortRange:
              From: 3389 
              To: 3389
  NaclAsstoPublicSubnet:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
         SubnetId: !Ref PublicSubnetCFN
         NetworkAclId: !Ref PublicNacl
         


  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPCCFN
      Tags:
        - Key: Name
          Value: PublicRouteTable
  publicRoutetoInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0	
      GatewayId: !Ref CFNIGW
  CFNIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CFNIGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPCCFN
      InternetGatewayId: !Ref CFNIGW
  AttachingRouteTabletoPublicSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetCFN
      RouteTableId: !Ref PublicRouteTable
  PrivateRoutetable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPCCFN
      Tags:
        - Key: Name
          Value: PrivateRouteTable
  AttachingRouteTabletoPrivateSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetCFN
      RouteTableId: !Ref PrivateRoutetable


          
  
