#Paramater:

  #MyVPCCidrBlock:
    #Type: AWS::EC2::VPCCidrBlock
    #Description: "myVPC CIDR block"
    #Default: 10.0.0.0/16

Resources:



  myVPCCFN:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: keyname
          Value: value
  PrivateSubnetCFN:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref myVPCCFN
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: keyname
          Value: value
  PublicSubnetCFN:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref myVPCCFN
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: keyname
          Value: value
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPCCFN
      Tags:
        - Key: keyname
          Value: value
  publicRoutetoInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt PublicRouteTable.RouteTableId
      DestinationCidrBlock: 0.0.0.0/0	
      GatewayId:
         Ref: CFNIGW
  CFNIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: keyname
          Value: value
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: vpc-id
      InternetGatewayId: 
        Ref: CFNIGW
    Type: AWS::EC2::InternetGateway
    Properties:
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPCCFN
      InternetGatewayId: 
        Ref: CFNIGW
  PrivateRoutetable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPCCFN
      Tags:
        - Key: keyname
          Value: value
  
