Parameters:

  MyVPCCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Description: "myVPC CIDR block"
    Default: 10.0.0.0/16
  
  AZ:
    Description: 
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a

Resources:



  myVPCCFN:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: myVPCCFN
  PrivateSubnetCFN:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      VpcId: !Ref myVPCCFN 
      CidrBlock: !Ref MyVPCCidrBlock
      Tags:
        - Key: Name
          Value: PrivateSubnetCFN
  PublicSubnetCFN:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      VpcId: !Ref myVPCCFN
      CidrBlock: !Ref MyVPCCidrBlock
      Tags:
        - Key: Name
          Value: PublicSubnetCFN
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPCCFN
      Tags:
        - Key: Name
          Value: PublicRouteTable
  publicRoutetoInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0	
      GatewayId: !Ref CFNIGW
  CFNIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CFNIGW
    Properties:
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPCCFN
      InternetGatewayId: !Ref CFNIGW
  AttachingRouteTabletoPublicSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetCFN
      RouteTableId: !Ref PublicRouteTable
  PrivateRoutetable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPCCFN
      Tags:
        - Key: Name
          Value: PrivateRouteTable
  AttachingRouteTabletoPrivateSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetCFN
      RouteTableId: !Ref PrivateRoutetable


          
  
